[package]
name = "arte-protocol"
version.workspace = true
edition.workspace = true

[dependencies]
async-std.workspace = true
bytes.workspace = true
thiserror.workspace = true
async-compression = { version = "0.4", features = ["futures-io", "zlib"] }
